create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  name text not null,
  role text not null check (role in ('superadmin', 'manager', 'member')),
  department_id bigint references public.departments(id) on delete set null,
  status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
  approved_at text,
  approved_by bigint references public.users(id) on delete set null,
  created_at text not null
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at text not null
);

create table if not exists public.task_categories (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.departments(id) on delete cascade,
  name text not null,
  created_at text not null,
  unique (department_id, name)
);

create table if not exists public.work_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  work_date text not null,
  department_id bigint not null references public.departments(id) on delete cascade,
  category_id bigint not null references public.task_categories(id) on delete cascade,
  hours numeric not null,
  detail text not null,
  created_at text not null
);

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;
